live_config_reload = true

[colors.bright]
black = "#888987"
blue = "#547c99"
cyan = "#7dd6cf"
green = "#879a3b"
  #purple = "#9f4e85"
red = "#be3f48"
white = "#fdffb9"
yellow = "#c47033"

[colors.cursor]
cursor = "#b9bcba"
text = "#1f1f1f"

[colors.normal]
black = "#3a3d43"
blue = "#4f76a1"
cyan = "#7dd6cf"
green = "#879a3b"
  #purple = "#855c8d"
red = "#be3f48"
white = "#b9bcba"
yellow = "#c5a635"

[colors.primary]
background = "#1f1f1f"
foreground = "#b9bcba"

[cursor]
blink_interval = 500
thickness = 0.2

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
y = -2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[90;5u"
key = "Z"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
  #decoration_theme_variant = "dark"
dynamic_title = true
  #startup_mode="Maximized"
